/*
* generated by Xtext
*/
package org.eclipselabs.spray.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SprayUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.spray.xtext.ui.internal.SprayActivator.getInstance().getInjector("org.eclipselabs.spray.xtext.Spray");
	}
	
}
