/*
* generated by Xtext
*/
package org.eclipselabs.spray.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.spray.xtext.services.SprayGrammarAccess;

public class SprayParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SprayGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.spray.xtext.parser.antlr.internal.InternalSprayParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.spray.xtext.parser.antlr.internal.InternalSprayParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Diagram";
	}
	
	public SprayGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SprayGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
