/*************************************************************************************
 *
 * Generated by Spray ConnectionDefinitionGenerator.xtend
 * 
 * This file is an extension point: copy to "src" folder to manually add code to this
 * extension point.
 *
 *************************************************************************************/
package org.eclipselabs.spray.examples.mod4j.shapes;

import org.eclipse.graphiti.features.IFeatureProvider;

public class AssociationConnectionConnection
		extends
			AssociationConnectionConnectionBase {

	public AssociationConnectionConnection(IFeatureProvider fp) {
		super(fp);
	}
}
