/*************************************************************************************
 *
 * Generated by Spray ShapeDefinitionGenerator.xtend
 * 
 * This file is an extension point: copy to "src" folder to manually add code to this
 * extension point.
 *
 *************************************************************************************/
package org.eclipselabs.spray.examples.mod4j.shapes;

import org.eclipse.graphiti.features.IFeatureProvider;

public class ClassShapeShape extends ClassShapeShapeBase {

	public ClassShapeShape(IFeatureProvider fp) {
		super(fp);
	}
}
