/*
* generated by Xtext
*/
package org.eclipselabs.spray.shapes;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ShapeUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.spray.shapes.ui.internal.ShapeActivator.getInstance().getInjector("org.eclipselabs.spray.shapes.Shape");
	}
	
}
