/*
* generated by Xtext
*/
package org.eclipselabs.spray.styles;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class StyleUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.spray.styles.ui.internal.StyleActivator.getInstance().getInjector("org.eclipselabs.spray.styles.Style");
	}
	
}
