/*
* generated by Xtext
*/
package org.eclipselabs.spray.styles.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.spray.styles.services.StyleGrammarAccess;

public class StyleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StyleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.spray.styles.parser.antlr.internal.InternalStyleParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.spray.styles.parser.antlr.internal.InternalStyleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StyleContainer";
	}
	
	public StyleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StyleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
