/**
 * Copyright (c)  The Spray Project.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Spray Dev Team - initial API and implementation
 */
package org.eclipselabs.spray.generator.graphiti.tests.mod4j.mod4j.features;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipselabs.spray.generator.graphiti.tests.AbstractSprayGeneratorTest;
import org.eclipselabs.spray.generator.graphiti.tests.SprayTestsInjectorProvider;

/* @RunWith(XtextRunner2.class) */@InjectWith(SprayTestsInjectorProvider.class)
@SuppressWarnings("all")
public class Mod4jAddReferenceBusinessClassSuperclassFeatureTest extends AbstractSprayGeneratorTest {
  /* @Test
   */public void test() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method assertTrue is undefined for the type Mod4jAddReferenceBusinessClassSuperclassFeatureTest"
      + "\nThe method assertEquals is undefined for the type Mod4jAddReferenceBusinessClassSuperclassFeatureTest");
  }
  
  private CharSequence expectedContent() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/*************************************************************************************");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Generated by Spray AddReferenceAsConnectionFeature.xtend");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* This file is an extension point: copy to \"src\" folder to manually add code to this");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* extension point.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*************************************************************************************/");
    _builder.newLine();
    _builder.append("package org.eclipselabs.spray.examples.mod4j.features;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.features.IFeatureProvider;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class Mod4jAddReferenceBusinessClassSuperclassFeature extends Mod4jAddReferenceBusinessClassSuperclassFeatureBase {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Mod4jAddReferenceBusinessClassSuperclassFeature(final IFeatureProvider fp) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("super(fp);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  /**");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//   * {@inheritDoc}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//   */");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  @Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  protected GraphicsAlgorithm createConnectionStartDecorator (final IAddConnectionContext context,");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//          final Connection connection) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      final ConnectionDecorator cd = peCreateService.createConnectionDecorator(");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//              connection, /* active */false, /* location */0.0, /* isRelative */");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//              true);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      final Polyline polyline = gaService.createPolyline(cd, new int[] {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//              -15, 10, 0, 0, -15, -10 });");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      polyline.setForeground(manageColor(IColorConstant.BLACK));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      polyline.setLineWidth(1);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      return polyline;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      return null;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  }");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  /**");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//   * {@inheritDoc}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//   */");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  @Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  protected GraphicsAlgorithm createConnectionEndDecorator (final IAddConnectionContext context,");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//          final Connection connection) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      final ConnectionDecorator cd = peCreateService.createConnectionDecorator(");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//              connection, /* active */false, /* location */1.0, /* isRelative */");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//              true);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      final Polygon polygon = gaService.createPolygon(cd, new int[] {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//              -12, 8, 0, 0, -12, -8, -12, 8 });");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      polygon.setForeground(manageColor(IColorConstant.BLACK));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      polygon.setBackground(manageColor(IColorConstant.WHITE));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      polygon.setFilled(Boolean.TRUE);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      polygon.setLineWidth(1);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//      return polygon;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("//  }");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
