/**
 * Copyright (c)  The Spray Project.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Spray Dev Team - initial API and implementation
 */
package org.eclipselabs.spray.generator.graphiti.tests.mod4j.mod4j.diagram;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipselabs.spray.generator.graphiti.tests.AbstractSprayGeneratorTest;
import org.eclipselabs.spray.generator.graphiti.tests.SprayTestsInjectorProvider;

/* @RunWith(XtextRunner2.class) */@InjectWith(SprayTestsInjectorProvider.class)
@SuppressWarnings("all")
public class Mod4jImageProviderBaseTest extends AbstractSprayGeneratorTest {
  /* @Test
   */public void test() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method assertTrue is undefined for the type Mod4jImageProviderBaseTest"
      + "\nThe method assertEquals is undefined for the type Mod4jImageProviderBaseTest");
  }
  
  private CharSequence expectedContent() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/*************************************************************************************");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Generated by Spray ImageProvider.xtend");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* This file contains generated and should not be changed.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Use the extension point class (the direct subclass of this class) to add manual code");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*************************************************************************************/");
    _builder.newLine();
    _builder.append("package org.eclipselabs.spray.examples.mod4j.diagram;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.ui.platform.AbstractImageProvider;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public abstract class Mod4jImageProviderBase extends AbstractImageProvider {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// The prefix for all identifiers of this image provider");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static final String PREFIX              = \"org.eclipselabs.spray.examples.mod4j.diagram.\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// The image identifier for an EReference.");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static final String MOD4J__ECORE_ECLASS = PREFIX + \"ecore_eclass\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* {@inheritDoc}");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected void addAvailableImages() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// register the path for each image identifier");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("addImageFilePath(MOD4J__ECORE_ECLASS, \"icons/ecore/EClass.gif\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
