/*
* generated by Xtext
*/
package org.eclipselabs.spray.shapes.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipselabs.spray.shapes.services.ShapeGrammarAccess;

public class ShapeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ShapeGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipselabs.spray.shapes.parser.antlr.internal.InternalShapeParser createParser(XtextTokenStream stream) {
		return new org.eclipselabs.spray.shapes.parser.antlr.internal.InternalShapeParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ShapeContainer";
	}
	
	public ShapeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ShapeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
