/*
 * generated by Xtext
 */
package org.eclipselabs.spray.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipselabs.spray.xtext.ui.internal.SprayActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SprayExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SprayActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SprayActivator.getInstance().getInjector(SprayActivator.ORG_ECLIPSELABS_SPRAY_XTEXT_SPRAY);
	}
	
}
