/*
 * generated by Xtext
 */
package org.eclipselabs.spray.styles.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipselabs.spray.styles.ui.internal.StyleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StyleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StyleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StyleActivator.getInstance().getInjector(StyleActivator.ORG_ECLIPSELABS_SPRAY_STYLES_STYLE);
	}
	
}
