/*
 * generated by Xtext
 */
package org.eclipselabs.spray.shapes.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipselabs.spray.shapes.ui.internal.ShapeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ShapeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ShapeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ShapeActivator.getInstance().getInjector(ShapeActivator.ORG_ECLIPSELABS_SPRAY_SHAPES_SHAPE);
	}
	
}
